locale: "en-US"
title:  "Brandon Jernigan, PhD"
title_separator: "-"
name: &name "Brandon Jernigan, PhD"
description: &description "Homepage for Brandon Jernigan"
url:  https://jun1u5.github.io
author:
  name: "Brandon Jernigan"
twitter:
  username: JUN1U5
social:
  links:
    - https://twitter.com/JUN1U5
    - http://www.linkedin.com/in/brandonjernigan
    - https://github.com/JUN1U5

permalink: /blog/:year/:month/:day/:title
highlighter: rouge
markdown: kramdown
exclude:
- README.md
plugins:
  - jekyll-seo-tag
